name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or main, if your default branch is named 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # use the Node.js version that matches your project

      - name: Install dependencies
        run: npm ci # or 'npm install', if you do not have a 'package-lock.json'

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # change this if your build outputs to a different directory
